apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-otlp
  labels:
    alertmanagerConfig: otlp
spec:
  route:
    groupBy: [ 'job' ]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
  receivers:
    - name: 'webhook'
      webhookConfigs:
        - url: 'http://example.com/' # this needs to agree with the configuration in the alertmanager secret