# for UI exposed from 'observability
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otlp-observability-test-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress-class
  rules:
    - host: hegemon.auto-instrument
      http:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: otel-test-service-auto
              port:
                number: 8080
    - host: hegemon.manual-instrument
      http:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: otel-test-service-manual
              port:
                number: 8080
  -

