# for UI exposed from 'elasctic-search
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otlp-elastic-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress-class
  rules:
    - host: elasticsearch.hegemon
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-es-http
                port:
                  number: 9200
    - host: kibana.hegemon
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-elasticsearch-kb-http
                port:
                  number: 5601

